import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <header className="p">
          <nav className="w-full">
            <div className="max"></div>
            <div className="max-w-7xl mx-auto px-6 md:pl-12 xl:px-6">
              <div className="flex flex-warp items-center justify-between">
                <div>
                 <a href="/">Logo</a>
                </div>
                <div>
                  <ul className="flex flex-row gap-6">
                    <li>
                      <a href="about">about</a>
                    </li>
                    <li>
                      <a href="contact">contact</a>
                    </li>
                    <li>
                      <a href="work">work</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
